/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MedicineId = IDL.Nat;
export const SellerId = IDL.Nat;
export const SellerMedicineId = IDL.Nat;
export const AppointmentId = IDL.Nat;
export const CustomerId = IDL.Nat;
export const SectionName = IDL.Text;
export const Medicine = IDL.Record({
  'id' : MedicineId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Customer = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
});
export const SellerStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Suspended' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Seller = IDL.Record({
  'id' : SellerId,
  'status' : SellerStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'documentsSubmitted' : IDL.Vec(IDL.Text),
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
});
export const SellerMedicine = IDL.Record({
  'id' : SellerMedicineId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : IDL.Text,
  'sellerId' : SellerId,
  'price' : IDL.Nat,
});
export const Appointment = IDL.Record({
  'id' : AppointmentId,
  'status' : IDL.Text,
  'submittedAt' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'patientName' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});
export const CustomerCredentials = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
});
export const SellerCredentials = IDL.Record({
  'id' : SellerId,
  'status' : SellerStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addMedicine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [MedicineId],
      [],
    ),
  'addSellerMedicine' : IDL.Func(
      [SellerId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [SellerMedicineId],
      [],
    ),
  'deleteAppointment' : IDL.Func([AppointmentId], [], []),
  'deleteCustomer' : IDL.Func([CustomerId], [], []),
  'deleteMedicine' : IDL.Func([MedicineId], [], []),
  'deleteSeller' : IDL.Func([SellerId], [], []),
  'deleteSellerMedicine' : IDL.Func([SellerMedicineId], [], []),
  'editMedicine' : IDL.Func(
      [MedicineId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'editSellerMedicine' : IDL.Func(
      [SellerMedicineId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'getAllContent' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(SectionName, IDL.Text))],
      ['query'],
    ),
  'getAvailableMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getContent' : IDL.Func([SectionName], [IDL.Text], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [Customer], ['query']),
  'getMedicalProduct' : IDL.Func([MedicineId], [Medicine], ['query']),
  'getMedicinesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Medicine)],
      ['query'],
    ),
  'getMedicinesSortedByPrice' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getSeller' : IDL.Func([SellerId], [Seller], ['query']),
  'getSellerByEmail' : IDL.Func([IDL.Text], [IDL.Opt(Seller)], ['query']),
  'listAllSellerMedicines' : IDL.Func([], [IDL.Vec(SellerMedicine)], ['query']),
  'listAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'listCustomerCredentials' : IDL.Func(
      [],
      [IDL.Vec(CustomerCredentials)],
      ['query'],
    ),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'listSellerCredentials' : IDL.Func(
      [],
      [IDL.Vec(SellerCredentials)],
      ['query'],
    ),
  'listSellerMedicines' : IDL.Func(
      [SellerId],
      [IDL.Vec(SellerMedicine)],
      ['query'],
    ),
  'listSellers' : IDL.Func([], [IDL.Vec(Seller)], ['query']),
  'loginCustomer' : IDL.Func([IDL.Text, IDL.Text], [Customer], ['query']),
  'loginSeller' : IDL.Func([IDL.Text, IDL.Text], [Seller], ['query']),
  'registerCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CustomerId],
      [],
    ),
  'registerSeller' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [SellerId],
      [],
    ),
  'searchMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
  'submitAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AppointmentId],
      [],
    ),
  'updateAppointmentStatus' : IDL.Func([AppointmentId, IDL.Text], [], []),
  'updateContent' : IDL.Func([SectionName, IDL.Text], [], []),
  'updateSellerStatus' : IDL.Func([SellerId, SellerStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MedicineId = IDL.Nat;
  const SellerId = IDL.Nat;
  const SellerMedicineId = IDL.Nat;
  const AppointmentId = IDL.Nat;
  const CustomerId = IDL.Nat;
  const SectionName = IDL.Text;
  const Medicine = IDL.Record({
    'id' : MedicineId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Customer = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SellerStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Suspended' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Seller = IDL.Record({
    'id' : SellerId,
    'status' : SellerStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'documentsSubmitted' : IDL.Vec(IDL.Text),
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SellerMedicine = IDL.Record({
    'id' : SellerMedicineId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : IDL.Text,
    'sellerId' : SellerId,
    'price' : IDL.Nat,
  });
  const Appointment = IDL.Record({
    'id' : AppointmentId,
    'status' : IDL.Text,
    'submittedAt' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'patientName' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  const CustomerCredentials = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SellerCredentials = IDL.Record({
    'id' : SellerId,
    'status' : SellerStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addMedicine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [MedicineId],
        [],
      ),
    'addSellerMedicine' : IDL.Func(
        [SellerId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [SellerMedicineId],
        [],
      ),
    'deleteAppointment' : IDL.Func([AppointmentId], [], []),
    'deleteCustomer' : IDL.Func([CustomerId], [], []),
    'deleteMedicine' : IDL.Func([MedicineId], [], []),
    'deleteSeller' : IDL.Func([SellerId], [], []),
    'deleteSellerMedicine' : IDL.Func([SellerMedicineId], [], []),
    'editMedicine' : IDL.Func(
        [MedicineId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'editSellerMedicine' : IDL.Func(
        [SellerMedicineId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'getAllContent' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(SectionName, IDL.Text))],
        ['query'],
      ),
    'getAvailableMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getContent' : IDL.Func([SectionName], [IDL.Text], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [Customer], ['query']),
    'getMedicalProduct' : IDL.Func([MedicineId], [Medicine], ['query']),
    'getMedicinesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Medicine)],
        ['query'],
      ),
    'getMedicinesSortedByPrice' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getSeller' : IDL.Func([SellerId], [Seller], ['query']),
    'getSellerByEmail' : IDL.Func([IDL.Text], [IDL.Opt(Seller)], ['query']),
    'listAllSellerMedicines' : IDL.Func(
        [],
        [IDL.Vec(SellerMedicine)],
        ['query'],
      ),
    'listAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'listCustomerCredentials' : IDL.Func(
        [],
        [IDL.Vec(CustomerCredentials)],
        ['query'],
      ),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'listSellerCredentials' : IDL.Func(
        [],
        [IDL.Vec(SellerCredentials)],
        ['query'],
      ),
    'listSellerMedicines' : IDL.Func(
        [SellerId],
        [IDL.Vec(SellerMedicine)],
        ['query'],
      ),
    'listSellers' : IDL.Func([], [IDL.Vec(Seller)], ['query']),
    'loginCustomer' : IDL.Func([IDL.Text, IDL.Text], [Customer], ['query']),
    'loginSeller' : IDL.Func([IDL.Text, IDL.Text], [Seller], ['query']),
    'registerCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CustomerId],
        [],
      ),
    'registerSeller' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [SellerId],
        [],
      ),
    'searchMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
    'submitAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AppointmentId],
        [],
      ),
    'updateAppointmentStatus' : IDL.Func([AppointmentId, IDL.Text], [], []),
    'updateContent' : IDL.Func([SectionName, IDL.Text], [], []),
    'updateSellerStatus' : IDL.Func([SellerId, SellerStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };