/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : AppointmentId,
  'status' : string,
  'submittedAt' : string,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'patientName' : string,
  'phone' : string,
  'department' : string,
}
export type AppointmentId = bigint;
export interface Customer {
  'id' : CustomerId,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'passwordHash' : string,
  'phone' : string,
}
export interface CustomerCredentials {
  'id' : CustomerId,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'passwordHash' : string,
  'phone' : string,
}
export type CustomerId = bigint;
export interface Medicine {
  'id' : MedicineId,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'price' : bigint,
}
export type MedicineId = bigint;
export type SectionName = string;
export interface Seller {
  'id' : SellerId,
  'status' : SellerStatus,
  'name' : string,
  'createdAt' : bigint,
  'documentsSubmitted' : Array<string>,
  'businessName' : string,
  'email' : string,
  'passwordHash' : string,
  'phone' : string,
}
export interface SellerCredentials {
  'id' : SellerId,
  'status' : SellerStatus,
  'name' : string,
  'createdAt' : bigint,
  'businessName' : string,
  'email' : string,
  'passwordHash' : string,
  'phone' : string,
}
export type SellerId = bigint;
export interface SellerMedicine {
  'id' : SellerMedicineId,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'sellerId' : SellerId,
  'price' : bigint,
}
export type SellerMedicineId = bigint;
export type SellerStatus = { 'Approved' : null } |
  { 'Suspended' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addMedicine' : ActorMethod<[string, string, bigint, string], MedicineId>,
  'addSellerMedicine' : ActorMethod<
    [SellerId, string, string, bigint, string],
    SellerMedicineId
  >,
  'deleteAppointment' : ActorMethod<[AppointmentId], undefined>,
  'deleteCustomer' : ActorMethod<[CustomerId], undefined>,
  'deleteMedicine' : ActorMethod<[MedicineId], undefined>,
  'deleteSeller' : ActorMethod<[SellerId], undefined>,
  'deleteSellerMedicine' : ActorMethod<[SellerMedicineId], undefined>,
  'editMedicine' : ActorMethod<
    [MedicineId, string, string, bigint, string, boolean],
    undefined
  >,
  'editSellerMedicine' : ActorMethod<
    [SellerMedicineId, string, string, bigint, string, boolean],
    undefined
  >,
  'getAllContent' : ActorMethod<[], Array<[SectionName, string]>>,
  'getAvailableMedicines' : ActorMethod<[], Array<Medicine>>,
  'getContent' : ActorMethod<[SectionName], string>,
  'getCustomer' : ActorMethod<[CustomerId], Customer>,
  'getMedicalProduct' : ActorMethod<[MedicineId], Medicine>,
  'getMedicinesByCategory' : ActorMethod<[string], Array<Medicine>>,
  'getMedicinesSortedByPrice' : ActorMethod<[], Array<Medicine>>,
  'getSeller' : ActorMethod<[SellerId], Seller>,
  'getSellerByEmail' : ActorMethod<[string], [] | [Seller]>,
  'listAllSellerMedicines' : ActorMethod<[], Array<SellerMedicine>>,
  'listAppointments' : ActorMethod<[], Array<Appointment>>,
  'listCustomerCredentials' : ActorMethod<[], Array<CustomerCredentials>>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listMedicines' : ActorMethod<[], Array<Medicine>>,
  'listSellerCredentials' : ActorMethod<[], Array<SellerCredentials>>,
  'listSellerMedicines' : ActorMethod<[SellerId], Array<SellerMedicine>>,
  'listSellers' : ActorMethod<[], Array<Seller>>,
  'loginCustomer' : ActorMethod<[string, string], Customer>,
  'loginSeller' : ActorMethod<[string, string], Seller>,
  'registerCustomer' : ActorMethod<
    [string, string, string, string],
    CustomerId
  >,
  'registerSeller' : ActorMethod<
    [string, string, string, string, string, Array<string>],
    SellerId
  >,
  'searchMedicines' : ActorMethod<[string], Array<Medicine>>,
  'submitAppointment' : ActorMethod<
    [string, string, string, string, string, string, string],
    AppointmentId
  >,
  'updateAppointmentStatus' : ActorMethod<[AppointmentId, string], undefined>,
  'updateContent' : ActorMethod<[SectionName, string], undefined>,
  'updateSellerStatus' : ActorMethod<[SellerId, SellerStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];