/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Seller {
    id: SellerId;
    status: SellerStatus;
    name: string;
    createdAt: bigint;
    documentsSubmitted: Array<string>;
    businessName: string;
    email: string;
    passwordHash: string;
    phone: string;
}
export type SellerId = bigint;
export interface CustomerCredentials {
    id: CustomerId;
    name: string;
    createdAt: bigint;
    email: string;
    passwordHash: string;
    phone: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Customer {
    id: CustomerId;
    name: string;
    createdAt: bigint;
    email: string;
    passwordHash: string;
    phone: string;
}
export type AppointmentId = bigint;
export interface SellerCredentials {
    id: SellerId;
    status: SellerStatus;
    name: string;
    createdAt: bigint;
    businessName: string;
    email: string;
    passwordHash: string;
    phone: string;
}
export type SectionName = string;
export type CustomerId = bigint;
export type MedicineId = bigint;
export interface Medicine {
    id: MedicineId;
    name: string;
    description: string;
    available: boolean;
    category: string;
    price: bigint;
}
export interface SellerMedicine {
    id: SellerMedicineId;
    name: string;
    createdAt: bigint;
    description: string;
    available: boolean;
    category: string;
    sellerId: SellerId;
    price: bigint;
}
export type SellerMedicineId = bigint;
export interface Appointment {
    id: AppointmentId;
    status: string;
    submittedAt: string;
    email: string;
    message: string;
    preferredDate: string;
    patientName: string;
    phone: string;
    department: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum SellerStatus {
    Approved = "Approved",
    Suspended = "Suspended",
    Rejected = "Rejected",
    Pending = "Pending"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addMedicine(name: string, description: string, price: bigint, category: string): Promise<MedicineId>;
    addSellerMedicine(sellerId: SellerId, name: string, description: string, price: bigint, category: string): Promise<SellerMedicineId>;
    deleteAppointment(id: AppointmentId): Promise<void>;
    deleteCustomer(id: CustomerId): Promise<void>;
    deleteMedicine(id: MedicineId): Promise<void>;
    deleteSeller(id: SellerId): Promise<void>;
    deleteSellerMedicine(id: SellerMedicineId): Promise<void>;
    editMedicine(id: MedicineId, name: string, description: string, price: bigint, category: string, available: boolean): Promise<void>;
    editSellerMedicine(id: SellerMedicineId, name: string, description: string, price: bigint, category: string, available: boolean): Promise<void>;
    getAllContent(): Promise<Array<[SectionName, string]>>;
    getAvailableMedicines(): Promise<Array<Medicine>>;
    getContent(section: SectionName): Promise<string>;
    getCustomer(id: CustomerId): Promise<Customer>;
    getMedicalProduct(id: MedicineId): Promise<Medicine>;
    getMedicinesByCategory(category: string): Promise<Array<Medicine>>;
    getMedicinesSortedByPrice(): Promise<Array<Medicine>>;
    getSeller(id: SellerId): Promise<Seller>;
    getSellerByEmail(email: string): Promise<Seller | null>;
    listAllSellerMedicines(): Promise<Array<SellerMedicine>>;
    listAppointments(): Promise<Array<Appointment>>;
    listCustomerCredentials(): Promise<Array<CustomerCredentials>>;
    listCustomers(): Promise<Array<Customer>>;
    listMedicines(): Promise<Array<Medicine>>;
    listSellerCredentials(): Promise<Array<SellerCredentials>>;
    listSellerMedicines(sellerId: SellerId): Promise<Array<SellerMedicine>>;
    listSellers(): Promise<Array<Seller>>;
    loginCustomer(email: string, passwordHash: string): Promise<Customer>;
    loginSeller(email: string, passwordHash: string): Promise<Seller>;
    registerCustomer(name: string, email: string, phone: string, passwordHash: string): Promise<CustomerId>;
    registerSeller(name: string, email: string, phone: string, businessName: string, passwordHash: string, documentDescriptions: Array<string>): Promise<SellerId>;
    searchMedicines(search: string): Promise<Array<Medicine>>;
    submitAppointment(patientName: string, phone: string, email: string, department: string, preferredDate: string, message: string, submittedAt: string): Promise<AppointmentId>;
    updateAppointmentStatus(id: AppointmentId, status: string): Promise<void>;
    updateContent(section: SectionName, content: string): Promise<void>;
    updateSellerStatus(id: SellerId, status: SellerStatus): Promise<void>;
}
import type { Seller as _Seller, SellerCredentials as _SellerCredentials, SellerId as _SellerId, SellerStatus as _SellerStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addMedicine(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<MedicineId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicine(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicine(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addSellerMedicine(arg0: SellerId, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<SellerMedicineId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSellerMedicine(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSellerMedicine(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteAppointment(arg0: AppointmentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: CustomerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteMedicine(arg0: MedicineId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0);
            return result;
        }
    }
    async deleteSeller(arg0: SellerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSeller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSeller(arg0);
            return result;
        }
    }
    async deleteSellerMedicine(arg0: SellerMedicineId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSellerMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSellerMedicine(arg0);
            return result;
        }
    }
    async editMedicine(arg0: MedicineId, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editMedicine(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMedicine(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async editSellerMedicine(arg0: SellerMedicineId, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editSellerMedicine(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editSellerMedicine(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async getAllContent(): Promise<Array<[SectionName, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContent();
            return result;
        }
    }
    async getAvailableMedicines(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableMedicines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableMedicines();
            return result;
        }
    }
    async getContent(arg0: SectionName): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContent(arg0);
            return result;
        }
    }
    async getCustomer(arg0: CustomerId): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return result;
        }
    }
    async getMedicalProduct(arg0: MedicineId): Promise<Medicine> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicalProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicalProduct(arg0);
            return result;
        }
    }
    async getMedicinesByCategory(arg0: string): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicinesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicinesByCategory(arg0);
            return result;
        }
    }
    async getMedicinesSortedByPrice(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicinesSortedByPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicinesSortedByPrice();
            return result;
        }
    }
    async getSeller(arg0: SellerId): Promise<Seller> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeller(arg0);
                return from_candid_Seller_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeller(arg0);
            return from_candid_Seller_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSellerByEmail(arg0: string): Promise<Seller | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSellerByEmail(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSellerByEmail(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllSellerMedicines(): Promise<Array<SellerMedicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllSellerMedicines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllSellerMedicines();
            return result;
        }
    }
    async listAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAppointments();
            return result;
        }
    }
    async listCustomerCredentials(): Promise<Array<CustomerCredentials>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomerCredentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomerCredentials();
            return result;
        }
    }
    async listCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers();
            return result;
        }
    }
    async listMedicines(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMedicines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMedicines();
            return result;
        }
    }
    async listSellerCredentials(): Promise<Array<SellerCredentials>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSellerCredentials();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSellerCredentials();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSellerMedicines(arg0: SellerId): Promise<Array<SellerMedicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSellerMedicines(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSellerMedicines(arg0);
            return result;
        }
    }
    async listSellers(): Promise<Array<Seller>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSellers();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSellers();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginCustomer(arg0: string, arg1: string): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.loginCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginCustomer(arg0, arg1);
            return result;
        }
    }
    async loginSeller(arg0: string, arg1: string): Promise<Seller> {
        if (this.processError) {
            try {
                const result = await this.actor.loginSeller(arg0, arg1);
                return from_candid_Seller_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginSeller(arg0, arg1);
            return from_candid_Seller_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerCustomer(arg0: string, arg1: string, arg2: string, arg3: string): Promise<CustomerId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async registerSeller(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>): Promise<SellerId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerSeller(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerSeller(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async searchMedicines(arg0: string): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMedicines(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMedicines(arg0);
            return result;
        }
    }
    async submitAppointment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<AppointmentId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAppointment(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAppointment(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateAppointmentStatus(arg0: AppointmentId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, arg1);
            return result;
        }
    }
    async updateContent(arg0: SectionName, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContent(arg0, arg1);
            return result;
        }
    }
    async updateSellerStatus(arg0: SellerId, arg1: SellerStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSellerStatus(arg0, to_candid_SellerStatus_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSellerStatus(arg0, to_candid_SellerStatus_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_SellerCredentials_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SellerCredentials): SellerCredentials {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_SellerStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SellerStatus): SellerStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Seller_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Seller): Seller {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Seller]): Seller | null {
    return value.length === 0 ? null : from_candid_Seller_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SellerId;
    status: _SellerStatus;
    name: string;
    createdAt: bigint;
    businessName: string;
    email: string;
    passwordHash: string;
    phone: string;
}): {
    id: SellerId;
    status: SellerStatus;
    name: string;
    createdAt: bigint;
    businessName: string;
    email: string;
    passwordHash: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_SellerStatus_n10(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        businessName: value.businessName,
        email: value.email,
        passwordHash: value.passwordHash,
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SellerId;
    status: _SellerStatus;
    name: string;
    createdAt: bigint;
    documentsSubmitted: Array<string>;
    businessName: string;
    email: string;
    passwordHash: string;
    phone: string;
}): {
    id: SellerId;
    status: SellerStatus;
    name: string;
    createdAt: bigint;
    documentsSubmitted: Array<string>;
    businessName: string;
    email: string;
    passwordHash: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_SellerStatus_n10(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        documentsSubmitted: value.documentsSubmitted,
        businessName: value.businessName,
        email: value.email,
        passwordHash: value.passwordHash,
        phone: value.phone
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Suspended: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): SellerStatus {
    return "Approved" in value ? SellerStatus.Approved : "Suspended" in value ? SellerStatus.Suspended : "Rejected" in value ? SellerStatus.Rejected : "Pending" in value ? SellerStatus.Pending : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SellerCredentials>): Array<SellerCredentials> {
    return value.map((x)=>from_candid_SellerCredentials_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Seller>): Array<Seller> {
    return value.map((x)=>from_candid_Seller_n8(_uploadFile, _downloadFile, x));
}
function to_candid_SellerStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SellerStatus): _SellerStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SellerStatus): {
    Approved: null;
} | {
    Suspended: null;
} | {
    Rejected: null;
} | {
    Pending: null;
} {
    return value == SellerStatus.Approved ? {
        Approved: null
    } : value == SellerStatus.Suspended ? {
        Suspended: null
    } : value == SellerStatus.Rejected ? {
        Rejected: null
    } : value == SellerStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
